services:
- type: web
  name: production-api-mavyn
  plan: pro
  env: docker
  region: ohio
  autoDeploy: false
  healthCheckPath: /healthz
  envVars:
  - key: HASURA_GRAPHQL_DATABASE_URL
    fromDatabase:
      name: production-api-mavyn
      property: connectionString
  - key: HASURA_GRAPHQL_ENABLE_CONSOLE
    value: true
  - key: HASURA_GRAPHQL_ADMIN_SECRET
    generateValue: true
  - key: HASURA_GRAPHQL_EXPERIMENTAL_FEATURES
    value: naming_convention
  - key: HASURA_GRAPHQL_DEFAULT_NAMING_CONVENTION
    value: graphql-default
  - key: HASURA_GRAPHQL_UNAUTHORIZED_ROLE
    value: anonymous
databases:
- name: production-api-mavyn
  postgresMajorVersion: 15
  region: ohio
  plan: pro
